//
//  SPPublishAppDelegate.m
//  SponsorPay iOS Test App
//
//  Copyright 2011-2013 SponsorPay. All rights reserved.
//

#import "SPSampleAppDelegate.h"
#import "SponsorPaySDK.h"

@implementation SPSampleAppDelegate

#pragma mark - Application lifecycle

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    SPLogSetLevel(SPLogLevelVerbose);
    self.window.rootViewController = self.viewController; // TODO clean this up
    [self.window makeKeyAndVisible];
    
    // By default, allows AutoGenerated user ids, since it's more convenient for our use.
    [[NSUserDefaults standardUserDefaults] registerDefaults:@{@"SPAllowAutoGeneratedUserId":@YES}];
    [[NSHTTPCookieStorage sharedHTTPCookieStorage] setCookieAcceptPolicy:NSHTTPCookieAcceptPolicyAlways];
    [self customizeAppearance];
    return YES;
}

#pragma mark - Shared among controllers

// TODO move this to SPTestAppBaseViewController

- (void)showSDKException:(NSException *)exception {
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"The SDK threw an exception"
                                                     message:exception.reason
                                                    delegate:self cancelButtonTitle:@"OK"
                                           otherButtonTitles:nil];
    [alert show];
}

- (void)customizeAppearance
{

}

@end
